apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
      - name: n8n
        image: n8nio/n8n:1.97.1
        ports:
        - containerPort: 5678
        volumeMounts:
        - name: n8n-data
          mountPath: /home/node/.n8n
        securityContext:
          runAsUser: 1000  
          runAsGroup: 1000 
        env:
        - name: TZ  
          value: "Europe/Paris"
        - name: GENERIC_TIMEZONE  
          value: "Europe/Paris"
        - name: N8N_BASIC_AUTH_ACTIVE
          value: "true"
        - name: N8N_BASIC_AUTH_USER
          valueFrom:
            secretKeyRef:
              name: n8n-secret
              key: N8N_BASIC_AUTH_USER
        - name: N8N_BASIC_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: n8n-secret
              key: N8N_BASIC_AUTH_PASSWORD
        - name: N8N_HOST
          value: "n8n.koden.bzh"
        - name: N8N_PORT
          value: "5678"
        - name: WEBHOOK_URL  
          value: "https://n8n.koden.bzh"
        - name: N8N_PAYLOAD_SIZE_MAX
          value: "50MB"
      volumes:
      - name: n8n-data
        persistentVolumeClaim:
          claimName: n8n-pvc
  strategy:
    type: Recreate
